SeyahatBlogSitesi/Models/Siniflar/SeyahatRehberi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SeyahatBlogSitesi.Models.Siniflar
{
    public class SeyahatRehberi
    {
        [Key]
        public int RehberID { get; set; }

        [Column(TypeName =("Varchar"))]
        [StringLength(30)]
        public string Rehber { get; set; }
        public string Aciklama { get; set; }

        public ICollection<BlogDetay> BlogDetays { get; set; }
    }
}

SeyahatBlogSitesi/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using SeyahatBlogSitesi.Models.Siniflar;

namespace SeyahatBlogSitesi.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog

        readonly Context c = new Context();
        readonly Class3 cs = new Class3();
        Class1 cs1 = new Class1();
        public ActionResult Index(int sayfa = 1)
        {
            var degerler = c.Blogs.Where(x => x.BlogTür == "Dünya").ToList().ToPagedList(sayfa, 8);
            return View(degerler);
        }
        public ActionResult Index2(int sayfa = 1)
        {
            var degerler = c.Blogs.Where(x => x.BlogTür == "Türkiye").ToList().ToPagedList(sayfa, 8);
            return View(degerler);
        }

        public PartialViewResult Partial1()
        {
            cs.Seyehat = c.Seyahatlers.ToList();
            cs.Rehber = c.SeyahatRehberis.ToList();
            return PartialView(cs);
        }
       
        public ActionResult BlogDetay(int id, string p)
        {
            var toplam = c.Yorumlars.Count(x => x.BlogID == id);
            if (toplam != 0)
            {
                ViewBag.d2 = toplam + " " + "Yorum";
            }
            else { }

          
            cs1.Blog = (from x in c.Blogs where x.ID == id select x).ToList();
            if(!string.IsNullOrEmpty(p))
            {
                cs1.Blog = cs1.Blog.Where(x => x.Giris.Contains(p) || x.Gelisme.Contains(p));
            }
            cs1.Rehber = c.SeyahatRehberis.ToList();
            return View(cs1);
        }

      
        public PartialViewResult YorumGetir(int id)
        {
            var d = c.Yorumlars.Where(x => x.BlogID == id).ToList();
            ViewBag.d1 = id;
            return PartialView(d);
        }

        public PartialViewResult SonrakiBlog(int id)
        {
            var s = c.Blogs.Where(x => x.ID > id).OrderBy(x => x.ID).Take(2).ToList();
            return PartialView(s);
        }

        [HttpGet]
        public PartialViewResult YorumEkle(int id)
        {
            var d = c.Yorumlars.Where(x => x.BlogID == id).ToList();
            ViewBag.d1 = id;
            return PartialView(d);
        }

        [HttpPost]
        public PartialViewResult YorumEkle(Yorumlar y)
        {
            c.Yorumlars.Add(y);
            c.SaveChanges();
            return PartialView();
        }

    }
}

SeyahatBlogSitesi/Controllers/SeyahatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using SeyahatBlogSitesi.Models.Siniflar;

namespace SeyahatBlogSitesi.Controllers
{
    public class SeyahatController : Controller
    {
        // GET: Seyahat
        Context c = new Context();
        Class3 cs = new Class3();

        public ActionResult Index(int id)
        {
            cs.Detay = (from x in c.BlogDetays
                        join y in c.SeyahatRehberis on
                        x.RehberID equals y.RehberID
                        where x.UlkeID == id & x.RehberID == 1
                        select x).ToList();
            ViewBag.d1 = id;
            cs.Rehber = c.SeyahatRehberis.ToList();
            cs.Yorumlar = c.Yorumlars.Where(x => x.BlogID == id).ToList();
            return View(cs);

        }

        public ActionResult Index2(int id, int idd)
        {
            cs.Detay = c.BlogDetays.Where(x => x.UlkeID == id & x.RehberID == idd).ToList();
            cs.Rehber = c.SeyahatRehberis.ToList();
            cs.Yorumlar = c.Yorumlars.Where(x => x.BlogID == id).ToList();
            ViewBag.d1 = id;
            return View(cs);
        }

        public ActionResult SeyahatRehberi(int id, int sayfa=1)
        {
            cs.Detay = c.BlogDetays.Where(x => x.RehberID == id).OrderBy(x => x.UlkeID).ToList().ToPagedList(sayfa,12);
            cs.Rehber = c.SeyahatRehberis.Where(x => x.RehberID == id).ToList();
            return View(cs);
        }
        public ActionResult SeyahatDetay(int id, int idd)
        {
            cs.Detay = c.BlogDetays.Where(x => x.UlkeID == id & x.RehberID == idd).ToList();
            cs.Rehber = c.SeyahatRehberis.ToList();
            cs.Yorumlar = c.Yorumlars.Where(x => x.BlogID == id).ToList();
            ViewBag.d1 = id;
            return View(cs);
        }

        public PartialViewResult SonrakiBlog(int id, int idd)
        {
            var s = c.BlogDetays.Where(x => x.RehberID == id & x.BlogID > idd).OrderBy(x => x.BlogID).Take(2).ToList();
            return PartialView(s);
        }
        public PartialViewResult SonrakiBlog2(int id, int idd)
        {
            var s = c.BlogDetays.Where(x => x.UlkeID > id & x.RehberID == idd).OrderBy(x => x.UlkeID).Take(2).ToList();
            return PartialView(s);
        }

    }
}

SeyahatBlogSitesi/Views/Seyahat/Index.cshtml
@model SeyahatBlogSitesi.Models.Siniflar.Class3
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<nav class="site-nav mt-3">
    <div class="container">

        @Html.Action("Partial1", "Blog")

    </div>
</nav>


<div class="hero overlay">
    <div class="img-bg rellax">
        @foreach (var x in Model.Detay)
        {
            <img src="@x.UlkeResim" alt="Image" class="img-fluid" style="width:1700px; height:650px">
        }
    </div>
    <div class="container">
        <div class="row align-items-center justify-content-start">
            <div class="col-lg-6 mx-auto text-center">
                <p> <a href="#"></a>  <a href="#"></a></p>
                <h1 class="heading" data-aos="fade-up" style="height:250px"></h1>
                <p data-aos="fade-up"></p>
            </div>
        </div>
    </div>
</div>


<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-8 blog-content pe-5">
                @foreach (var x in Model.Detay)
                {
                    <p class="lead">@x.Baslik</p>
                    <p>@x.Giris</p>
                    <img src="@x.Resim1" class="img-fluid" style="height:412px; width:914px">
                    <br /><br />
                    <blockquote><p>@x.Gelisme</p></blockquote>
                    <img src="@x.Resim2" class="img-fluid" style="height:412px; width:914px">
                    <br /><br />
                    <p>@x.Sonuc</p>
                    <img src="@x.Resim3" class="img-fluid" style="height:412px; width:914px"><br /><br />

                    if (x.Detay != null)
                    { <blockquote><p>@x.Detay</p></blockquote>
                    <img src="@x.Resim4" class="img-fluid" style="height:412px; width:914px">
                    <br /><br />
                }
                else { }


                if (x.Detay1 != null)
                {
                    <p>@x.Detay1</p>
                    <img src="@x.Resim5" class="img-fluid" style="height:412px; width:914px">
                    <br /><br />
                }
                else { }
                <div class="pt-5">
                    <p>Seyehat Rehberi:  <a href="">@x.SeyahatRehberi.Rehber </a>, <a href=""># </a> &nbsp;  Konum: <a href="#">@x.Seyahatler.UlkeAD</a>, <a href="">#</a></p>
                </div>
            }

            <div class="pt-5">
                <h3 class="mb-5">@ViewBag.d2</h3>
                <ul class="comment-list">
                    @foreach (var x in Model.Yorumlar)
                    {
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="~/untree.co-sterial/images/17605.png" />
                            </div>
                            <div class="comment-body">
                                <h3>@x.KullaniciAdi</h3>
                                <div class="meta">January 9, 2018 at 2:21pm</div>
                                <p>@x.Yorum</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                    }
                </ul>

                @Html.Action("YorumEkle", "Blog")

            </div>

            </div>
            <div class="col-md-4 sidebar">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon fa fa-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>

                <div class="sidebar-box">
                    <div class="categories">
                        <h3>Seyahat Rehberi</h3>
                        @foreach (var x in Model.Rehber)
                        {
                            <li>
                                <a href="/Seyahat/Index2/@ViewBag.d1/@x.RehberID">@x.Rehber</a>
                            </li>
                        }
                    </div>
                </div>

               @Html.Action("SonrakiBlog2", "Seyahat")
            </div>
        </div>
    </div>
</div>

SeyahatBlogSitesi/Views/Seyahat/Index2.cshtml
@model SeyahatBlogSitesi.Models.Siniflar.Class3
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<nav class="site-nav mt-3">
    <div class="container">

        @Html.Action("Partial1", "Blog")

    </div>
</nav>


<div class="hero overlay">
    <div class="img-bg rellax">
        @foreach (var x in Model.Detay)
        {
            <img src="@x.UlkeResim" alt="Image" class="img-fluid" style="width:1700px; height:650px">
        }
    </div>
    <div class="container">
        <div class="row align-items-center justify-content-start">
            <div class="col-lg-6 mx-auto text-center">
                <p> <a href="#"></a>  <a href="#"></a></p>
                <h1 class="heading" data-aos="fade-up" style="height:250px"></h1>
                <p data-aos="fade-up"></p>
            </div>
        </div>
    </div>
</div>


<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-8 blog-content pe-5">
                @foreach (var x in Model.Detay)
                {
                    <p class="lead">@x.Baslik</p>
                    <p>@x.Giris</p>
                    <img src="@x.Resim1" class="img-fluid" style="height:412px; width:914px">
                    <br /><br />
                    <blockquote><p>@x.Gelisme</p></blockquote>
                    <img src="@x.Resim2" class="img-fluid" style="height:412px; width:914px">
                    <br /><br />
                    <p>@x.Sonuc</p>
                    <img src="@x.Resim3" class="img-fluid" style="height:412px; width:914px">
                    <br /><br />

                    if (x.Detay != null)
                    { <blockquote><p>@x.Detay</p></blockquote>
                    <img src="@x.Resim4" class="img-fluid" style="height:412px; width:914px">
                    <br /><br />
                }
                else { }


                if (x.Detay1 != null)
                {
                    <p>@x.Detay1</p>
                    <img src="@x.Resim5" class="img-fluid" style="height:412px; width:914px">
                    <br /><br />
                }
                else { }
            }

                <div class="pt-5">
                    <h3 class="mb-5">@ViewBag.d2</h3>
                    <ul class="comment-list">
                        @foreach (var x in Model.Yorumlar)
                        {
                            <li class="comment">
                                <div class="vcard bio">
                                    <img src="~/untree.co-sterial/images/17605.png" />
                                </div>
                                <div class="comment-body">
                                    <h3>@x.KullaniciAdi</h3>
                                    <div class="meta">January 9, 2018 at 2:21pm</div>
                                    <p>@x.Yorum</p>
                                    <p><a href="#" class="reply">Reply</a></p>
                                </div>
                            </li>
                        }
                    </ul>

                    @Html.Action("YorumEkle", "Blog")

                </div>

            </div>
            <div class="col-md-4 sidebar">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon fa fa-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>

                <div class="sidebar-box">
                    <div class="categories">
                        <h3>Seyahat Rehberi</h3>
                        @foreach (var x in Model.Rehber)
                        {
                            <li>
                                <a href="/Seyahat/Index2/@ViewBag.d1/@x.RehberID">@x.Rehber</a>
                            </li>
                        }
                    </div>
                </div>

                @Html.Action("SonrakiBlog2", "Seyahat")
            </div>
        </div>
    </div>
</div>

SeyahatBlogSitesi/Views/Seyahat/SeyahatDetay.cshtml
@model SeyahatBlogSitesi.Models.Siniflar.Class3
@{
    ViewBag.Title = "SeyahatDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<nav class="site-nav mt-3">
    <div class="container">

        @Html.Action("Partial1", "Blog")

    </div>
</nav>


<div class="hero overlay">
    @foreach (var x in Model.Detay)
    {
        <div class="img-bg rellax">
            <img src="@x.UlkeResim" class="img-fluid" style="width:1700px; height:650px">
        </div>
    }

    <div class="container">
        <div class="row align-items-center justify-content-start">
            <div class="col-lg-6 mx-auto text-center">
                <p> <a href="#"></a>  <a href="#"></a></p>
                <h1 class="heading" data-aos="fade-up" style="height:250px"></h1>
                <p data-aos="fade-up"></p>
            </div>
        </div>
    </div>
</div>


    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-8 blog-content pe-5">
                    @foreach (var x in Model.Detay)
                    {
                        <p class="lead">@x.Baslik</p>
                        <p>@x.Giris</p>
                        <img src="@x.Resim1" class="img-fluid" style="height:412px; width:914px">
                        <br /><br />
                        <blockquote><p>@x.Gelisme</p></blockquote>
                        <img src="@x.Resim2" class="img-fluid" style="height:412px; width:914px">
                        <br /><br />
                        <p>@x.Sonuc</p>
                        <img src="@x.Resim3" class="img-fluid" style="height:412px; width:914px"><br /><br />

                        if (x.Detay != null)
                        { <blockquote><p>@x.Detay</p></blockquote>
                        <img src="@x.Resim4" class="img-fluid" style="height:412px; width:914px">
                        <br /><br />
                    }
                    else { }


                    if (x.Detay1 != null)
                    {
                        <p>@x.Detay1</p>
                        <img src="@x.Resim5" class="img-fluid" style="height:412px; width:914px">
                        <br /><br />
                    }
                    else { }
                    <div class="pt-5">
                        <p>Seyehat Rehberi:  <a href="">@x.SeyahatRehberi.Rehber </a>, <a href=""># </a> &nbsp;  Konum: <a href="#">@x.Seyahatler.UlkeAD</a>, <a href="">#</a></p>
                    </div>
                }

                    <div class="pt-5">
                        <h3 class="mb-5">@ViewBag.d2</h3>
                        <ul class="comment-list">
                            @foreach (var x in Model.Yorumlar)
                            {
                                <li class="comment">
                                    <div class="vcard bio">
                                        <img src="~/untree.co-sterial/images/17605.png" />
                                    </div>
                                    <div class="comment-body">
                                        <h3>@x.KullaniciAdi</h3>
                                        <div class="meta">January 9, 2018 at 2:21pm</div>
                                        <p>@x.Yorum</p>
                                        <p><a href="#" class="reply">Reply</a></p>
                                    </div>
                                </li>
                            }
                        </ul>

                        @Html.Action("YorumEkle", "Blog")

                    </div>


                </div>
                <div class="col-md-4 sidebar">
                    <div class="sidebar-box">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon fa fa-search"></span>
                                <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box">
                        <div class="categories">
                            <h3>Seyahat Rehberi </h3>
                            @foreach (var x in Model.Rehber)
                            {
                                <li>
                                    <a href="/Seyahat/Index2/@ViewBag.d1/@x.RehberID">@x.Rehber</a>
                                </li>
                            }
                        </div>

                    </div>

                    @Html.Action("SonrakiBlog2", "Seyahat")
                </div>
        </div>
    </div>
</div>

SeyahatBlogSitesi/Views/Seyahat/SeyahatRehberi.cshtml
@using PagedList
@using PagedList.Mvc
@model SeyahatBlogSitesi.Models.Siniflar.Class3
@{
    ViewBag.Title = "SeyahatRehberi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<nav class="site-nav mt-3">
    <div class="container">

        @Html.Action("Partial1", "Blog")

    </div>
</nav>


<div class="hero overlay">

    <div class="img-bg rellax">
        <img src="~/untree.co-sterial/images/img-4.jpg" class="img-fluid" style="width:1700px; height:700px" />
    </div>


    <div class="container">
        <div class="row align-items-center justify-content-start">
            <div class="col-lg-5">
                <h1 class="heading" data-aos="fade-up">“Turistler nereye gittiklerini, </h1>
                <p class="mb-5" data-aos="fade-up">
                    gezginler nereye gideceklerini bilemezler.” <br />
                    <i style="float:right">Paul Theroux </i>
                </p>
            </div>
        </div>
    </div>
</div>


<div class="section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-lg-6 mx-auto text-center">
                <div class="heading-content" data-aos="fade-up">
                    @foreach (var x in Model.Rehber)
                    {
                        <h2> @x.Rehber</h2>
                        <p>@x.Aciklama</p>
                    }

                    <p class="my-4" data-aos="fade-up" data-aos-delay="300"><a href="#" class="btn btn-primary">View All</a></p>
                </div>
            </div>
        </div>

        <div class="row">
            @foreach (var s in Model.Detay)
            {
                <div class="col-lg-3">
                    <div class="bg-white m-body">
                        <div class="service-2 left-0 mb-5">
                            <img src="@s.UlkeResim" class="img-fluid mb-4 rounded" style="width:350px; height:300px;">
                            <span class="date">@s.Tarih.ToShortDateString() @s.Tarih.ToShortTimeString()</span>
                            <div>
                                <a href="/Seyahat/SeyahatDetay/@s.UlkeID/@s.RehberID"><h3>@s.Baslik</h3></a>
                                <p>@s.Giris.Substring(0, 100)</p>
                                <p><a href="/Seyahat/SeyahatDetay/@s.UlkeID/@s.RehberID" class="more">Devamını Oku</a></p>
                            </div>
                        </div>

                    </div>

                </div>
            }
        </div>

        <div class="pagination" style="justify-content:center">
            @Html.PagedListPager((IPagedList)Model.Detay, sayfa => Url.Action("SeyahatRehberi", new { sayfa }), new PagedListRenderOptions
            {
                LiElementClasses = new List<string>
                { "page-link" }
            })
        </div>
    </div>
</div>

SeyahatBlogSitesi/Views/Seyahat/SonrakiBlog.cshtml
@using SeyahatBlogSitesi.Models.Siniflar
@model List<BlogDetay>

@foreach (var x in Model)
{
    <div class="sidebar-box">
        @*<img src="@x.BlogImage" class="img-fluid mb-4 w-50 rounded-circle ">*@
        <h3 class="text-black">@x.Baslik</h3>
        <p>@x.Giris.Substring(0, 100)...</p>
        <p><a href="/Blog/BlogDetay/@x.UlkeID/@x.RehberID" class="btn btn-primary btn-md text-white">Devamını oku</a></p>
    </div>
}

SeyahatBlogSitesi/Views/Seyahat/SonrakiBlog2.cshtml
@using SeyahatBlogSitesi.Models.Siniflar
@model List<BlogDetay>

@foreach (var x in Model)
{

    <div class="sidebar-box">
        @*<img src="@x.BlogImage" class="img-fluid mb-4 w-50 rounded-circle ">*@
        <h3 class="text-black">@x.Baslik</h3>
        <p>@x.Giris.Substring(0, 200)...</p>
        <p><a href="/Seyahat/SeyahatDetay/@x.UlkeID/@x.RehberID" class="btn btn-primary btn-md text-white" >Devamını oku</a></p>
    </div>
}